### ISSUE TITLE
Saving models to h5

### ISSUE THREAD

**Issue by makemate** [qubvel/segmentation_models#101]
I have trained Unet with resnet101 backbone successfully and was able to save and load them. 
`model_checkpoint = ModelCheckpoint(model_path,monitor='metric',  mode = 'max', save_best_only=True, `verbose=1)`
When I'm training U-net with Resnext101 as backbone the training in the notebook freezes when it tries the first time to save the model. There is enough space on the disk and no error message appears. Is this a general issue with larger models in keras or is there a bug in the repo?

Thanks in advance!

**Comment by qubvel** [comment]
Hi, I don't know why, but the first time saving the model takes more time. And with *Xt models it is significantly larger because keras/tf doesn't have a native support of grouped conv layer, and it is implemented as a set of smaller conv layers (actually 32 group conv layer implemented as 32 separate layers), so saving it takes a lot of time.

**Comment by makemate** [comment]
Thanks, you were right. I was just too impatient and saving the model took longer than expected.
