### ISSUE TITLE
Mask Shape for RGBA

### ISSUE THREAD

**Issue by johanneskpp** [qubvel/segmentation_models#152]
Which shape do my masks need if i use rgba images for training? I'm using the ImageDataGenerator and fit_generator method. Does it work with black and white RGB-Masks with 3 channels?

**Comment by qubvel** [comment]
Hi @johanneskpp   
```
image shape = [batch_size, height, width, num_channels]  
mask_shape =  [batch_size, height, width, num_classes] 
 # dont forget background class if num_classes > 1
```
As you see, mask shape does not depend on how many channels have your input image.

**Comment by JordanMakesMaps** [comment]
@qubvel , regarding the background class, how should one denote it so that it is not included in the loss and predictions? Currently I have actual classes [1:7], and one I call 'background' which has a pixel value of 0 in my masks. I'm finding that the background class is actually being considered as a class like the others, when what I actually want is for those pixels to be completely ignored during training and not considered an option in prediction. Thoughts?

Thanks.

**Comment by qubvel** [comment]
for loss and metrics added `class_indexes` parameter in new version, look at v1.0.0b1

**Comment by JordanMakesMaps** [comment]
@qubvel thanks!
