### ISSUE TITLE
[Not issue] SEresnet unet 

### ISSUE THREAD

**Issue by rupeshs** [qubvel/segmentation_models#24]
Please add pretrained seresnet unet segmentation models

**Comment by qubvel** [comment]
Hi @rupeshs, 
I am currently working on it. However there are some difficulties:
1) I was not able to find ImageNet trained se-resnet models on Keras
2) Converting from Pytorch with MMdnn and pytorch2keras frameworks failed due to specific layers
So, models have to be trained from scratch and it take some time.
