### ISSUE TITLE
accuracy dropped to 0.49% after 57 epoch

### ISSUE THREAD

**Issue by wenze-shui** [qubvel/segmentation_models#256]
Hello, my training process was normal before 50, but the accuracy dropped to 0.49 after 57 epoch.I use unet+vgg16. 
![image](https://user-images.githubusercontent.com/44524397/68759006-dee2b480-0649-11ea-9f0b-182e3105c6c2.png)

**Comment by TimbusCalin** [comment]
Hi wenze-shui. The reason why this happens is that VGG16, as compared to other networks which use skip-connections, suffer from the vanishing gradient problem. 

This also happened to me, so if you train too much and too deep your network will start to have vanishing gradient issues (in your case after epoch 56), that's why you have those extremely poor results.

**Comment by wenze-shui** [comment]
> 嗨，文泽水。发生这种情况的原因是，与使用跳过连接的其他网络相比，VGG16遭受了梯度消失的困扰。
> 
> 这也发生在我身上，因此，如果您训练得太多和太深，您的网络就会开始消失梯度问题（对于情况而言，在第56纪之后），这就是为什么您获得这些结果极差的原因。

Thank you very much
