### ISSUE TITLE
How do i get image classification score?

### ISSUE THREAD

**Issue by invite-you** [qubvel/segmentation_models#292]
It wonderfully found the location of car, pedestrians.
But I don't know what percentage of their accuracy.
Could you please tell me how to get the classification accuracy?
I referenced  https://github.com/qubvel/segmentation_models/blob/master/examples/multiclass segmentation (camvid).ipynb

**Comment by christianayala10** [comment]
Are you asking for the overall accuracy or the accuracy for an specific image?

**Comment by invite-you** [comment]
> Are you asking for the overall accuracy or the accuracy for an specific image?

The accuracy for each label. If there are people and cats in an image, I would like to display 90% chance of being human and 63% chance of being cat.

**Comment by christianayala10** [comment]
In the notebook you have referenced ([link](https://github.com/qubvel/segmentation_models/blob/master/examples/multiclass%20segmentation%20(camvid).ipynb)) there is a section called **"Visualization of results on test dataset"** in which random test predictions are performed. Specifically, this line:
```
pr_mask = model.predict(image)
```

returns `pr_mask` which is an array of size `W x H x C` containing the classification probabilities.

**Comment by invite-you** [comment]
Thank you for your kind response.

`pr_mask` is a numpy array.

> array([[[[0.19035003, 0.08304802, 0.72660196],
>          [0.05176399, 0.08008447, 0.86815155],
>          [0.06353691, 0.06593811, 0.870525  ],
>          ...,
>          [0.01299685, 0.03443719, 0.9525659 ],
>          [0.01437833, 0.04461242, 0.9410092 ],
>          [0.05679349, 0.03155244, 0.9116541 ]],

In here, how big is the possibility of the mask being a car? How can I find it?
If you can show me a short example code, I will be able to understand. 
I want to find possibilities like the image in this [link](https://github.com/xuannianz/EfficientDet/blob/master/test/000010.jpg).

**Comment by JordanMakesMaps** [comment]
So the link you provided is the result of an object detection algorithm, the results from this architecture is going to be different. See the illustration below from Jeremy Jordan's site as a reference:

![one-hot-endcoded-example](https://user-images.githubusercontent.com/8714759/73849638-439c4e00-47f8-11ea-86f0-7abeb4b8c8af.PNG)

What you can do is say whether or not a car is present in the image (by simple determining if the highest probabilities for any one pixel belongs to the class 'car'). You might run into an issue here though, because if your model isn't sufficiently trained, you might have one or two pixels that are labeled as 'car' even though a car isn't actually in the image. So you could go a further step by first finding all of the pixels that are likely to belong to 'car', and then divide that by the total number of pixels in the image, if that percentage is higher than a threshold that you set, then you dub that there is in fact a car in the image.

That's just one way of doing it, but I implore you to look for other ways (and report your results back here if you can 😁)

With the `pr_mask` numpy array you can do:
```python
pr_mask = model.predict(np.expand_dims(img, axis = 0)).squeeze()
# pr_mask.shape == (H, W, C)

pr_mask = np.argmax(pr_mask, axis = 2) 
# pr_mask.shape == (H, W)

# to count the occurrences, say car is equal to 3 in the pr_mask
num_car_pixels = numpy.count_nonzero(pr_mask == 3)
percent_car_pixels = (num_car_pixels / (H * W)) * 100 
```
Something like that.

**Comment by invite-you** [comment]
After I got contour from object, I applied your suggestion.
Thank you for kind answer! 😁
